'use client';
import { useLocale } from 'next-intl';
import DocLayout from '../../components/DocLayout';
import {
  P,
  H2,
  UL,
  LI,
  Table,
  InfoCard,
  Code,
} from '../../components/DocProse';

export default function RevenuePage() {
  const isUrdu = useLocale() === 'ur';

  return (
    <DocLayout
      title='Revenue Tracking'
      titleUr='آمدنی ٹریکنگ'
      description='Monitor consultation fees, period-based revenue reports, and per-doctor performance.'
      breadcrumbs={[
        {
          label: 'Clinic Administration',
          href: '/docs/clinic-administration/dashboard',
        },
        { label: 'Revenue' },
      ]}
      lastUpdated='June 2026'
      readingTime='5 min read'
    >
      {isUrdu ? (
        <>
          <P>
            کلینک ایڈمن سسٹم کی مکمل آمدنی کی نگرانی کر سکتا ہے۔ اس میں ہر ڈاکٹر
            کی کارکردگی، مشاورت کی فیس، اور مختلف ادوار کی بنیاد پر آمدنی کا
            تفصیلی تجزیہ شامل ہوتا ہے۔
          </P>

          <H2>آمدنی کا ماخذ</H2>
          <P>
            ہر مکمل ہونے والی ملاقات کے بعد سسٹم خودکار طور پر ایک آمدنی ریکارڈ
            بناتا ہے۔ اس میں ڈاکٹر، مریض، اپائنٹمنٹ اور فیس کی مکمل تفصیل محفوظ
            کی جاتی ہے۔
          </P>

          <H2>آمدنی کا ڈھانچہ</H2>
          <Table
            headers={['فیلڈ', 'قسم', 'تفصیل']}
            rows={[
              ['amount', 'Number', 'مشاورت کی فیس (PKR)'],
              ['doctorId', 'ObjectId', 'آمدنی پیدا کرنے والا ڈاکٹر'],
              ['appointmentId', 'ObjectId', 'مکمل شدہ اپائنٹمنٹ'],
              ['patientId', 'ObjectId', 'مریض کا ریکارڈ'],
              ['createdAt', 'Date', 'آمدنی بننے کا وقت'],
            ]}
          />

          <H2>آمدنی کی رپورٹس</H2>
          <UL>
            <LI>کل آمدنی کا گراف — ہفتہ وار اور ماہانہ آمدنی کا تجزیہ</LI>
            <LI>ڈاکٹر کی کارکردگی — ہر ڈاکٹر کی آمدنی کا موازنہ</LI>
            <LI>ٹارگٹ رپورٹ — مقررہ اہداف کے مقابلے میں کارکردگی</LI>
            <LI>ایکسپورٹ فیچر — CSV فائل میں مکمل ڈیٹا ڈاؤن لوڈ</LI>
          </UL>

          <InfoCard variant='info' title='کرنسی سسٹم'>
            تمام آمدنی پاکستانی روپے (PKR) میں محفوظ اور ظاہر کی جاتی ہے۔ اردو
            موڈ میں فارمیٹنگ ur-PK جبکہ انگریزی موڈ میں en-PK لوکل کے مطابق ہوتی
            ہے۔
          </InfoCard>
        </>
      ) : (
        <>
          <P>
            The Revenue module tracks all consultation fee income generated by
            the clinic...
          </P>

          <H2>Revenue Entry Structure</H2>
          <P>
            Each RevenueEntry document captures appointment, doctor, and patient
            data...
          </P>

          <Table
            headers={['Field', 'Type', 'Description']}
            rows={[
              ['amount', 'Number', 'Consultation fee in PKR'],
              ['doctorId', 'ObjectId', 'Doctor generating revenue'],
              ['appointmentId', 'ObjectId', 'Completed appointment'],
              ['patientId', 'ObjectId', 'Patient reference'],
              ['createdAt', 'Date', 'Completion timestamp'],
            ]}
          />

          <H2>Revenue Reports</H2>
          <UL>
            <LI>Total revenue chart by time period</LI>
            <LI>Per-doctor earnings breakdown</LI>
            <LI>Target vs actual comparison</LI>
            <LI>CSV export for accounting</LI>
          </UL>

          <InfoCard variant='info' title='Currency'>
            All amounts are stored in PKR and formatted using locale-aware
            formatting.
          </InfoCard>
        </>
      )}
    </DocLayout>
  );
}
