'use client';
import { useLocale } from 'next-intl';
import DocLayout from '../../components/DocLayout';
import {
  P,
  H2,
  UL,
  LI,
  Table,
  InfoCard,
  Code,
} from '../../components/DocProse';

export default function ClinicDashboardPage() {
  const isUrdu = useLocale() === 'ur';

  return (
    <DocLayout
      title='Clinic Admin Dashboard'
      titleUr='کلینک ایڈمن ڈیش بورڈ'
      description="Full operational overview — today's patients, revenue, active doctors, and appointment flow."
      breadcrumbs={[
        {
          label: 'Clinic Administration',
          href: '/docs/clinic-administration/dashboard',
        },
        { label: 'Dashboard' },
      ]}
      lastUpdated='June 2026'
      readingTime='6 min read'
    >
      {isUrdu ? (
        <>
          <P>
            کلینک ایڈمن ڈیش بورڈ کلینک کے انتظامی امور کا مرکزی کنٹرول پینل ہے۔
            یہاں کلینک کی مجموعی کارکردگی، آج کے مریض، آمدنی، فعال ڈاکٹرز اور
            اپائنٹمنٹس کا مکمل جائزہ ایک ہی جگہ پر دستیاب ہوتا ہے۔
          </P>

          <H2>اہم میٹرکس</H2>
          <P>
            اس سیکشن میں کلینک کی بنیادی کارکردگی کے اعداد و شمار دکھائے جاتے
            ہیں جو ریئل ٹائم میں اپ ڈیٹ ہوتے ہیں۔ یہ ڈیٹا کلینک کے تمام ڈاکٹروں
            اور مریضوں کے ریکارڈ سے حاصل کیا جاتا ہے۔
          </P>

          <H2>مریضوں کا بہاؤ (Patient Flow)</H2>
          <P>
            یہ گراف پچھلے 30 دنوں میں روزانہ آنے والے مریضوں کی تعداد دکھاتا ہے۔
            اس کا مقصد کلینک کے مصروف دنوں کی شناخت اور بہتر منصوبہ بندی میں مدد
            دینا ہے۔
          </P>

          <H2>اپائنٹمنٹ اوورویو</H2>
          <P>
            اس سیکشن میں آج کے تمام اپائنٹمنٹس دکھائے جاتے ہیں جو کلینک کے تمام
            ڈاکٹروں سے متعلق ہوتے ہیں۔ ایڈمن انہیں فلٹر کر کے ڈاکٹر، اسٹیٹس یا
            وقت کے مطابق دیکھ سکتا ہے۔
          </P>

          <H2>فوری ایکشنز</H2>
          <UL>
            <LI>
              نیا ڈاکٹر شامل کریں — ای میل کے ذریعے ڈاکٹر کو کلینک میں مدعو کریں
            </LI>
            <LI>نیا اسٹاف شامل کریں — ریسیپشن یا سپورٹ اسٹاف اکاؤنٹ بنائیں</LI>
            <LI>ریونیو رپورٹ دیکھیں — مکمل مالی تفصیلات تک رسائی</LI>
            <LI>کلینک سیٹنگز — اوقات، معلومات اور پروفائل اپڈیٹ کریں</LI>
          </UL>

          <InfoCard variant='tip' title='اینالیٹکس سنیپ شاٹ سسٹم'>
            تفصیلی اینالیٹکس رات 2 بجے چلنے والے خودکار سنیپ شاٹ جابز کے ذریعے
            تیار کی جاتی ہیں۔ یہ سسٹم ڈیٹا کو پہلے سے پروسیس کر کے ڈیش بورڈ کو
            تیز اور مؤثر بناتا ہے۔
          </InfoCard>
        </>
      ) : (
        <>
          <P>
            The Clinic Administration Dashboard provides the operational command
            center for clinic managers...
          </P>

          <H2>Key Metrics</H2>

          <Table
            headers={['Metric', 'Source', 'Update Frequency']}
            rows={[
              [
                "Today's Total Patients",
                "Appointments with today's date",
                'Real-time on load',
              ],
              [
                'Total Revenue',
                'Sum of all RevenueEntry records',
                'Real-time on load',
              ],
              [
                'Active Doctors',
                'Doctors with isActive=true in clinic',
                'Real-time on load',
              ],
              [
                'Pending Appointments',
                'Appointments with status=pending',
                'Real-time on load',
              ],
              [
                'Monthly Revenue',
                'RevenueEntry sum for current month',
                'Real-time on load',
              ],
            ]}
          />

          <H2>Patient Flow Chart</H2>
          <P>A line chart shows patient visit counts per day...</P>

          <H2>Appointment Queue Overview</H2>
          <P>A table shows all appointments across all clinic doctors...</P>

          <H2>Quick Actions</H2>
          <UL>
            <LI>
              Add Doctor — invite a new doctor to join the clinic by email
            </LI>
            <LI>Add Staff — create a receptionist or support staff account</LI>
            <LI>View Revenue Report — jump to detailed revenue breakdown</LI>
            <LI>
              Clinic Settings — update working hours, contact info, and clinic
              profile
            </LI>
          </UL>

          <InfoCard variant='tip' title='Analytics snapshot jobs'>
            Detailed analytics are generated by nightly snapshot jobs at 2 AM...
          </InfoCard>
        </>
      )}
    </DocLayout>
  );
}
